# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: sparkfun_pro_micro_rp2040
    shield: klor_left
  - board: sparkfun_pro_micro_rp2040
    shield: klor_right
  - board: sparkfun_pro_micro_rp2040
    shield: settings_reset
  # Debug builds with USB logging
  - board: sparkfun_pro_micro_rp2040
    shield: klor_left
    snippet: zmk-usb-logging
    artifact-name: klor_left_debug
  - board: sparkfun_pro_micro_rp2040
    shield: klor_right
    snippet: zmk-usb-logging
    artifact-name: klor_right_debug
